"""scripts

Revision ID: 08631c6589ac
Revises: 
Create Date: 2024-01-16 22:09:15.618716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08631c6589ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
